version: '3'

services:
  janus-gateway:
    build:
      context: .
    restart: unless-stopped
    tty: true
    image: sailorpapay/janus-webrtc
    ports:
      - "8080:80"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
    
    
   
